telegram:
  bot:
    token: 7846398531:AAHzFiS03qOCBHFBcLFEt9zLDGR2QXfBpfI
    username: @ShopInKilsoyFreeBot
admin:
  id: 1487264229
spring:
  datasource:
    url: jdbc:sqlite:/app/orders.db
    driver-class-name: org.sqlite.JDBC